### ISSUE TITLE
Updating Book Code to DeepChem 2.4.0

### ISSUE THREAD

**Issue by rbharath** [deepchem/DeepLearningLifeSciences#26]
We need to work to update the book code to DeepChem 2.4.0. I've gotten a report on gitter than the chapter 6 code isn't working. What else do we need to update?

CC @peastman

**Comment by myjenniferr22** [comment]
Hi! I am reading "Deep Learning for the Life Sciences" right now. So far I realized that two parts of codes could not be run. The first one is under page 78 (in Chapter 5):
`tasks, datasets,trasformers = dc.molnet.load_pdbbind(featurizer='grid', split='random', subset='core`)

The second one is under page 91 (in Chpater 6). The whole blocks of codes can't be run. This is what I found so far, and there might will have more because of the updates. 

Thank you very much for your help!!!! :-D
 
-Jennifer

**Comment by myjenniferr22** [comment]
Also, for the first error I mentioned above (the one under page 78). I tried to redefine `featurizer = 'grid` as `featurizer = grid_featurizer`, and `grid_featurizer` had been already defined in page 77.  After this small change, it works for that line. 

However, when I tried to run the code after that, 

`sklearn_model = RandomForestRegressor(n_estimators=100)
model= dc.models.SklearnModel(sklearn_model)
model.fit(train_dataset)`,

it shows me another error that `ValueError: Found array with 0 feature(s) (shape=(3881, 0)) while a minimum of 1 is required.
`.

**Comment by myjenniferr22** [comment]
Also, I found same problem in Chapter 7, page 120. 

`model = dc.models.TensorGraph(learning_rate=learning_rate, model_dir='model')`

It will still report me like:

`AttributeError: module 'deepchem.models' has no attribute 'TensorGraph'`''

I believe similar type of error went through the whole book since we are all using DeepChem 2.4.0 now. Please let me know if there is anything I can help with :-D. So far this is the problem that I still stick with. Thank you!

**Comment by myjenniferr22** [comment]
Another error found in chapter 7 page 124:

`image_dir = 'BBBC005_v1_images'
label_dir = 'BBBC005_v1_ground_truth'
rows = ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P')
blurs = (1, 4, 7, 10, 14, 17, 20, 23, 26, 29, 32, 35, 39, 42, 45, 48)
files = []
labels = []
for f in os.listdir(label_dir):
    if f.endswith('.TIF'):
        for row,blur in zip(rows, blurs):
            fname = f.replace('_F1', '_F%d'%blur).replace('_A','_%s'%row)
            files.append(os.path.join(image_dir, fname))
            labels.append(os.path.join(label_dir,f))

loader = dc.data.ImageLoader()
dataset = loader.featurize(files, labels)
splitter = dc.splits.RandomSplitter()
train_dataset, valid_dataset, test_dataset = splitter.train_valid_test_split(dataset, seed=123)`

When I run this code following the instruction from: https://github.com/deepchem/DeepLearningLifeSciences/blob/master/Chapter07/cell_segmentation.py, it sends me an error that shows `IndexError: list index out of range`,

**Comment by rbharath** [comment]
Thank you for the reports! I'm currently working through another bug right now, but will turn around and try to fix some of these once I'm done with that bug.

**Comment by peastman** [comment]
I can go through all the book examples and bring them up to date.

**Comment by myjenniferr22** [comment]
> Thank you for the reports! I'm currently working through another bug right now, but will turn around and try to fix some of these once I'm done with that bug.

Thank you very much!!! Also, Deep Learning for the Life Sciences is such an amazing book!! Thank you for all the efforts you put into this book! I super enjoy when read it!!!!

**Comment by myjenniferr22** [comment]
> I can go through all the book examples and bring them up to date.

Thank you very much!!! Please let me know anytime if there is anything I could help with. I am reading through the book right now and will not stop until I finish the whole book!! :-D Nice book, I love it!!

**Comment by peastman** [comment]
Thank you!  I'm really glad you're enjoying it.  We really need to do an updated edition one of these days, since so much has changed in DeepChem.  For example, the whole TensorGraph framework doesn't exist anymore in 2.4.  We've moved to Keras and PyTorch as our modelling APIs.  In the mean time, we'll try to keep the examples in the repository up to date.

**Comment by peastman** [comment]
Note to self: we need to see if there's a way to speed up RdkitGridFeaturizer.  We use it for the PDBBind examples in chapter 5.  Prevously we just specified `featurizer="grid"`, and that told it to download a pre-featurized version of the dataset.  But now we actually run the featurization locally, and it's *really* slow.

**Comment by myjenniferr22** [comment]
> Thank you! I'm really glad you're enjoying it. We really need to do an updated edition one of these days, since so much has changed in DeepChem. For example, the whole TensorGraph framework doesn't exist anymore in 2.4. We've moved to Keras and PyTorch as our modelling APIs. In the mean time, we'll try to keep the examples in the repository up to date.

Thank you very much for your reply! I will keep reporting the errors/issues from the book here. Please let me know anytime if there is any other things I could help with code update. I am extremely excited that I can talk directly with the author of this fascinating book! This world is magical!!!! :-D

**Comment by myjenniferr22** [comment]
Error in **Chapter 8 page 146**:

Because we want to use `DRModel` to define and build model, we first import valid module following the codebook: 

`from model import DRModel, DRAccuracy, ConfusionMatric, QuadWeightedKappa`

And there is an error says `ModuleNotFoundError: No module named 'model'`.

**Comment by peastman** [comment]
The featurization was still running when I went to bed, which had been about eight hours.  It had finished when I got up this morning.  But the result seems to be rather messed up.  The `X` array is a 1D array containing arrays, rather than a 2D array.  About 10% of those arrays have 0 length, apparently because featurization failed on those molecules.  And a few elements are `None`.

@rbharath do you have any ideas about what's going on?

**Comment by rbharath** [comment]
Hmm, not sure. My first guess is that perhaps the options are set incorrectly? `RdkitGridFeaturizer` can generate both voxels and flat feature vectors and the options need to be set to generate the flat feature vectors.

Unfortunately, the `RdkitGridFeaturizer` has been due for a major overhaul for a while. I'm working on fixing `AtomicConvModel` right now but I can make my next project a pass over `RdkitGridFeaturizer` to stabilize and document the code

**Comment by rbharath** [comment]
Ah that's definitely a bug then! It shouldn't be behaving like that.

**Comment by myjenniferr22** [comment]
Issues find in Chapter 9 page 158 (I am not so sure everyone has the sample problem with me, but just in case I will still post it here):

`model.fit_sequences(generate_sequences(50))`

This command line takes way longer time than expected. I tried five times, it just keeps running and never stop. The shortest time it takes is 3 hour. It runs 3 hour, but sill shows `In [*]`.

**Comment by peastman** [comment]
You want a good GPU for running that example.  Doing it on a CPU would take a very long time.

**Comment by myjenniferr22** [comment]
> You want a good GPU for running that example. Doing it on a CPU would take a very long time.

Thank you very much! I am always thinking it's might caused by my computer :-D Since it is not a bug caused by version update, I will delete that comment then. I will also post all errors in the whole book caused by deepchem version change here before next Monday. Thank you very much for all your help! As a newbie in this area, I am so glad that I have the opportunity to directly talk to the author of this fascinating book and get involved!  LOVE IT!!!!! Enjoy your weekend!!!

**Comment by myjenniferr22** [comment]
Error update: Chapter 11 page 187, from first block of codes: 

`loader = dc.data.CSVLoader(tasks=tasks, smiles_field="SMILES", featurizer=featurizer)`

should be revised as (because new version does not support `smiles_field` anymore): 

`loader = dc.data.CSVLoader(tasks=tasks, feature_field="SMILES", featurizer=featurizer)`

**Comment by myjenniferr22** [comment]
Error update: Chapter 11 page 185, from last lock of codes: 

`training_score_list = []
validation_score_list = []
transformers = []
cv_folds = 10
for i in range(0,cv_folds):
    model = generate_graph_conv_model()
    train_dataset, valid_dataset, test_dataset = splitter.train_valid_test_split(dataset)
    model.fit(train_dataset)
    train_scores = model.evaluate(train_dataset, metrics, transformers)
    training_score_list.append(train_scores["mean-matthews_corrcoef"])
    validation_scores = model.evaluate(valid_dataset, metrics, transformers)
    validation_score_list.append(validation_scores["mean-matthews_corrcoef"])
    print(training_score_list)
    print(validation_score_list)`

The error reports `Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets`

**Comment by myjenniferr22** [comment]
Hi Dr. Ramsundar and Dr. Eastman, 

So far I've updated all errors I found in the book. Greatly appreciated all your help!! I will keep working on reviewing them and finding the best solution. Please let me know anytime if there is anything I could help with :-D Hope you two have a lovely day!

Sincerely, 

-Jennifer Ma

**Comment by ZkrKarry** [comment]
> Error update: Chapter 11 page 185, from last lock of codes:
> 
> `training_score_list = [] validation_score_list = [] transformers = [] cv_folds = 10 for i in range(0,cv_folds): model = generate_graph_conv_model() train_dataset, valid_dataset, test_dataset = splitter.train_valid_test_split(dataset) model.fit(train_dataset) train_scores = model.evaluate(train_dataset, metrics, transformers) training_score_list.append(train_scores["mean-matthews_corrcoef"]) validation_scores = model.evaluate(valid_dataset, metrics, transformers) validation_score_list.append(validation_scores["mean-matthews_corrcoef"]) print(training_score_list) print(validation_score_list)`
> 
> The error reports `Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets`

I also encountered the same error, have you found a solution?

**Comment by rbharath** [comment]
@ZkrKarry Fixes are in #27 and should be merged in soon!
